codecov:
  require_ci_to_pass: yes
  coverage:
  status:
  patch: no
  project:
  default:
  threshold: 1%
  if_not_found: success
  changes: no
  precision: 2
  range: "35...100"
  ignore:
    - "test/.*"
    - "**/SqlMapper.java"
    - ".github/.*"
    - "docs/.*"
    - "*.md"
      comment:
      layout: "reach,diff,flags,tree"
      behavior: default
      require_changes: no